-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/10/2015 2:56:45 AM
-- Server version: 5.6.17
-- Client version: 4.1

--
-- Definition for database test
--
DROP DATABASE IF EXISTS grmsys_db;
CREATE DATABASE grmsys_db
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/22/2015 2:45:44 AM
-- Server version: 5.6.26-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE grmsys_db;

--
-- Definition for table item_sales_details
--
DROP TABLE IF EXISTS item_sales_details;
CREATE TABLE item_sales_details (
  item_sales_id INT(11) NOT NULL,
  item_id INT(11) NOT NULL,
  qty SMALLINT(6) NOT NULL DEFAULT 0,
  unit_total DECIMAL(10, 0) NOT NULL DEFAULT 0,
  remarks TEXT DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  creation_date DATETIME DEFAULT NULL,
  INDEX UK_item_sales_details_item_sal (item_sales_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1820
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Sales details table';

--
-- Definition for table service_type
--
DROP TABLE IF EXISTS service_type;
CREATE TABLE service_type (
  type_code VARCHAR(25) NOT NULL,
  type_name VARCHAR(50) NOT NULL,
  price_daily DECIMAL(10, 2) DEFAULT NULL,
  price_daily_discounted DECIMAL(19, 2) DEFAULT NULL,
  price_monthly DECIMAL(10, 2) DEFAULT NULL,
  price_monthly_discounted DECIMAL(19, 2) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  user_id INT(11) NOT NULL DEFAULT 1,
  creation_date DATETIME NOT NULL,
  last_modified_date DATETIME DEFAULT NULL,
  UNIQUE INDEX UK_service_type_type_code (type_code),
  UNIQUE INDEX unique_service_type (type_code, type_name)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Service Type Table';

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(100) NOT NULL,
  firstname VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  contactno VARCHAR(25) DEFAULT NULL,
  address MEDIUMTEXT DEFAULT NULL,
  birthdate DATE DEFAULT NULL,
  gender CHAR(1) NOT NULL DEFAULT 'M',
  is_active TINYINT(4) NOT NULL DEFAULT 1,
  role_type VARCHAR(50) NOT NULL DEFAULT 'attendant',
  creation_date DATETIME NOT NULL,
  last_modified_date DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  UNIQUE INDEX profilename_unique (firstname, lastname, middlename),
  UNIQUE INDEX username_UNIQUE (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 1049
AVG_ROW_LENGTH = 1092
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'System Users Table containing user information. This table could be divided into plain user login info and user profile infos.';

--
-- Definition for table item
--
DROP TABLE IF EXISTS item;
CREATE TABLE item (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  price DECIMAL(11, 2) NOT NULL DEFAULT 0.00,
  other_info TEXT DEFAULT NULL,
  user_id INT(10) UNSIGNED NOT NULL DEFAULT 1,
  creation_date DATETIME DEFAULT NULL,
  last_modified_date DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  UNIQUE INDEX name_unique (name),
  CONSTRAINT FK_item_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 107
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table member
--
DROP TABLE IF EXISTS member;
CREATE TABLE member (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  contactno VARCHAR(25) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  birthdate DATE DEFAULT NULL,
  gender CHAR(1) DEFAULT 'M',
  emergency_contact_person VARCHAR(125) NOT NULL,
  emergency_contact_number VARCHAR(25) NOT NULL,
  emergency_contact_relationship VARCHAR(45) NOT NULL,
  creation_date DATETIME NOT NULL,
  last_modified_date DATETIME DEFAULT NULL,
  user_id INT(10) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  UNIQUE INDEX profilename_unique (firstname, lastname, middlename),
  CONSTRAINT fk_member_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1015
AVG_ROW_LENGTH = 1638
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'System members table. This table holds info regarding membership profile(s).';

--
-- Definition for table item_sales
--
DROP TABLE IF EXISTS item_sales;
CREATE TABLE item_sales (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  grand_total_amount DECIMAL(11, 2) NOT NULL,
  sales_date DATETIME NOT NULL,
  member_id INT(11) UNSIGNED DEFAULT NULL,
  user_id INT(10) UNSIGNED NOT NULL DEFAULT 1,
  creation_date TEXT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  CONSTRAINT fk_item_sales_member_id FOREIGN KEY (member_id)
    REFERENCES member(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_item_sales_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 17
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table membership_type
--
DROP TABLE IF EXISTS membership_type;
CREATE TABLE membership_type (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  member_id INT(10) UNSIGNED NOT NULL,
  type VARCHAR(15) DEFAULT 'Daily',
  discounted TINYINT(1) DEFAULT 0,
  service_type VARCHAR(15) DEFAULT 'weights',
  monthly_startdate DATE DEFAULT NULL,
  monthly_enddate DATE DEFAULT NULL,
  creation_date DATETIME NOT NULL,
  last_modified_date DATETIME DEFAULT NULL,
  user_id INT(10) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  CONSTRAINT fk_membership_type_default_service_type FOREIGN KEY (service_type)
    REFERENCES service_type(type_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_membership_type_member_id FOREIGN KEY (member_id)
    REFERENCES member(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_membership_type_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 1638
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Membership Type table. Holds information about the type of membership like walk-in/monthly, services applied, discounted, etc.';

--
-- Definition for table workout_sales
--
DROP TABLE IF EXISTS workout_sales;
CREATE TABLE workout_sales (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  member_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  workout_date DATE NOT NULL,
  workout_hour INT(11) DEFAULT NULL,
  service_type VARCHAR(15) NOT NULL DEFAULT 'weights',
  rendered_amount DECIMAL(11, 2) NOT NULL DEFAULT 0.00,
  paid VARCHAR(10) DEFAULT '0',
  other_info TEXT DEFAULT NULL,
  user_id INT(10) UNSIGNED NOT NULL DEFAULT 1,
  creation_date DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_member_id_idx (member_id),
  INDEX fk_user_id_idx (user_id),
  UNIQUE INDEX id_UNIQUE (id),
  UNIQUE INDEX unique_workout (member_id, workout_date, workout_hour),
  CONSTRAINT fk_workout_sales_member_id FOREIGN KEY (member_id)
    REFERENCES member(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_workout_sales_service_type FOREIGN KEY (service_type)
    REFERENCES service_type(type_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_workout_sales_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 10037
AVG_ROW_LENGTH = 862
CHARACTER SET utf8
COLLATE utf8_general_ci;

DELIMITER $$

--
-- Definition for procedure pAddOrUpdateItem
--
DROP PROCEDURE IF EXISTS pAddOrUpdateItem$$
CREATE PROCEDURE pAddOrUpdateItem(IN pItemId INT, IN pItemName VARCHAR(100), IN pItemPrice DECIMAL(11,2), IN pOtherInfo TEXT, IN pUserId INT)
  SQL SECURITY INVOKER
BEGIN
  IF 0 < pItemId THEN
    UPDATE item SET
      name = pItemName,
      price = pItemPrice,
      other_info = pOtherInfo,
      last_modified_date = now()
    WHERE id = pItemId;
  ELSE
    INSERT INTO item(name, price, other_info, user_id, creation_date, last_modified_date) VALUES(pItemName, pItemPrice, pOtherInfo, pUserId, now(), now());
  END IF;

  COMMIT;
END
$$

--
-- Definition for procedure pAddOrUpdateMemberInfo
--
DROP PROCEDURE IF EXISTS pAddOrUpdateMemberInfo$$
CREATE PROCEDURE pAddOrUpdateMemberInfo(IN pMemberId varchar(255), IN pFirstname varchar(50), IN pLastname varchar(50), IN pMiddlename varchar(50), IN pContactNo varchar(50), IN pAddress text, IN pBirthdate VARCHAR(25), IN pGender char(1), IN pEmergencyContactPerson varchar(255), IN pEmergencyContactNo varchar(50), IN pEmergencyContactRelation varchar(50), IN pMemberType varchar(255), IN pHasDiscount tinyint, IN pMemberServiceType varchar(255), IN pMonthlyStartDate VARCHAR(25), IN pMonthlyEndDate varchar(25), IN pUserId int(10))
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for adding member and member type.'
BEGIN
  IF 0 < pMemberId THEN

    SET @sqlStmt = CONCAT('UPDATE member SET firstname= ''', pFirstname,''', lastname= ''', pLastname,''', middlename= ''', pMiddlename,''', contactno= ''', pContactNo,''', address= ''', pAddress,''', ');
    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, 'birthdate=''', pBirthdate, ''', ');
    END IF;
    SET @sqlStmt = CONCAT(@sqlStmt, 'gender=''', pGender, ''', emergency_contact_person=''', pEmergencyContactPerson, ''', emergency_contact_number=''', pEmergencyContactNo, ''', emergency_contact_relationship=''', pEmergencyContactRelation, ''', last_modified_date=now() WHERE id=', pMemberId);

    SET @sqlStmtType = CONCAT('UPDATE membership_type SET type= ''', pMemberType, ''', discounted=''', pHasDiscount, ''', service_type=''', pMemberServiceType, ''', ');
    SET @sqlStmtType = CONCAT(@sqlStmtType, 'last_modified_date=now() WHERE member_id=', pMemberId);

    IF pMemberType = 'Monthly' AND !ISNULL(pMonthlyStartDate) AND !ISNULL(pMonthlyEndDate) THEN
      SET @sqlUpdateStmtType = CONCAT('UPDATE membership_type SET monthly_startdate=''', pMonthlyStartDate, ''', ', 'monthly_enddate=''', pMonthlyEndDate, ''', ', 'last_modified_date=now() WHERE member_id=', pMemberId);
    ELSE
      SET @sqlUpdateStmtType = CONCAT('UPDATE membership_type SET monthly_startdate=null, ', 'monthly_enddate=null, ', 'last_modified_date=now() WHERE member_id=', pMemberId);
    END IF;

  ELSE

    SET @sqlStmt = CONCAT('INSERT INTO MEMBER (firstname, lastname, middlename, contactno, address, ');
    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, 'birthdate,');
    END IF;
    SET @sqlStmt = CONCAT(@sqlStmt, 'gender, emergency_contact_person, emergency_contact_number, emergency_contact_relationship, user_id, creation_date, last_modified_date)');
    SET @sqlStmt = CONCAT(@sqlStmt, ' VALUES (''', pFirstname, ''', ''', pLastname, ''', ''', pMiddlename, ''', ''', pContactNo, ''', ''', pAddress, ''',''');
    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, pBirthdate, ''', ''');
    END IF;
    SET @sqlStmt = CONCAT(@sqlStmt, pGender, ''', ''', pEmergencyContactPerson, ''', ''', pEmergencyContactNo, ''', ''', pEmergencyContactRelation, ''', ''', pUserId, ''', now(), now())');


    SET @sqlStmtType = CONCAT('INSERT INTO MEMBERSHIP_TYPE (member_id, type, discounted, service_type,');
    IF pMemberType = 'Monthly' AND !ISNULL(pMonthlyStartDate) THEN
      SET @sqlStmtType = CONCAT(@sqlStmtType, ' monthly_startdate,');
    END IF;
    IF pMemberType = 'Monthly' AND !ISNULL(pMonthlyEndDate) THEN
      SET @sqlStmtType = CONCAT(@sqlStmtType, ' monthly_enddate,');
    END IF;
    SET @sqlStmtType = CONCAT(@sqlStmtType, ' user_id, creation_date, last_modified_date) VALUES (LAST_INSERT_ID(),''');
    SET @sqlStmtType = CONCAT(@sqlStmtType, pMemberType, ''' , ''', pHasDiscount, ''', ''' , pMemberServiceType, ''', ''');
    IF !ISNULL(pMonthlyStartDate) THEN
      SET @sqlStmtType = CONCAT(@sqlStmtType, pMonthlyStartDate, ''' , ''');
    END IF;
    IF !ISNULL(pMonthlyEndDate) THEN
      SET @sqlStmtType = CONCAT(@sqlStmtType, pMonthlyEndDate, ''' , ''');
    END IF;
    SET @sqlStmtType = CONCAT(@sqlStmtType, pUserId, ''', now(), now())');

  END IF;

  PREPARE stmt FROM @sqlStmt;
  EXECUTE stmt;
  DEALLOCATE PREPARE stmt;

  PREPARE stmtType FROM @sqlStmtType;
  EXECUTE stmtType;
  DEALLOCATE PREPARE stmtType;

  IF 0 < pMemberId THEN
    PREPARE stmtTypeUpdate FROM @sqlUpdateStmtType;
    EXECUTE stmtTypeUpdate;
    DEALLOCATE PREPARE stmtTypeUpdate;
  END IF;

END
$$

--
-- Definition for procedure pAddOrUpdateUser
--
DROP PROCEDURE IF EXISTS pAddOrUpdateUser$$
CREATE PROCEDURE pAddOrUpdateUser(IN pUserId INT, IN pUsername VARCHAR(50), IN pPassword VARCHAR(255), IN pFirstname VARCHAR(50), IN pLastname VARCHAR(50), IN pMiddlename VARCHAR(50), IN pContactNo VARCHAR(25), IN pAddress TEXT, IN pBirthdate VARCHAR(25), IN pGender CHAR(1), IN pType VARCHAR(255))
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for Adding or Updating User'
BEGIN
  IF 0 < pUserId THEN
    SET @sqlStmt = CONCAT('UPDATE User SET ','firstname=''', pFirstname, ''', lastname=''', pLastname, ''', middlename=''', pMiddlename, ''', contactno=''', pContactNo, ''', address=''',  pAddress);

    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, ''', birthdate=''', pBirthdate);
    END IF;

    SET @sqlStmt = CONCAT(@sqlStmt, ''', gender=''', pGender, ''', role_type=''', pType, ''', last_modified_date=now() WHERE id=', pUserId);
  ELSE
    SET @sqlStmt = CONCAT('INSERT INTO User(username, password, firstname, lastname, middlename, contactno, address,');
    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, ' birthdate,');
    END IF;
    SET @sqlStmt = CONCAT(@sqlStmt, ' gender, is_active, role_type, creation_date, last_modified_date) VALUES (''', pUsername, ''', md5(''',pPassword,'''), ''',pFirstname,''', ''', pLastname,''', ''', pMiddlename,''', ''',pContactNo,''', ''', pAddress,''',''');
    IF !ISNULL(pBirthdate) THEN
      SET @sqlStmt = CONCAT(@sqlStmt, pBirthdate, ''', ''');
    END IF;
    SET @sqlStmt = CONCAT(@sqlStmt, pGender, ''', 1, ''', pType, ''', now(), now())');
  END IF;

  PREPARE stmt FROM @sqlStmt;
  EXECUTE stmt;
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Definition for procedure pAddSellItem
--
DROP PROCEDURE IF EXISTS pAddSellItem$$
CREATE PROCEDURE pAddSellItem(IN pItemId INT, IN pItemQty VARCHAR(255), IN pTotalAmount DECIMAL, IN pMemberId INT, IN pUserId INT)
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for Adding sell item'
BEGIN
  INSERT INTO item_sales(item_id, qty, amount, sales_date, member_id, user_id) VALUES(pItemId, pItemQty, pTotalAmount, now(), pMemberId, pUserId);
  COMMIT;
END
$$

--
-- Definition for procedure pAddUpdateServiceType
--
DROP PROCEDURE IF EXISTS pAddUpdateServiceType$$
CREATE PROCEDURE pAddUpdateServiceType(IN pTypeCode VARCHAR(25), IN pTypeName VARCHAR(50), IN pPriceDaily DECIMAL, IN pPriceDailyDiscounted DECIMAL, IN pPriceMonthly DECIMAL, IN pPriceMonthlyDiscounted DECIMAL, IN pRemarks TEXT, IN pUserId INT)
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for adding or updating service type'
BEGIN
  DECLARE stypeCount INT;
  SELECT count(type_code) into stypeCount FROM service_type WHERE type_code = pTypeCode;
  IF 0 < stypeCount THEN
    -- Update
    UPDATE service_type SET
      type_name = pTypeName,
      price_daily = pPriceDaily,
      price_daily_discounted = pPriceDailyDiscounted,
      price_monthly = pPriceMonthly,
      price_monthly_discounted = pPriceMonthlyDiscounted,
      last_modified_date = now()
    WHERE type_code = pTypeCode;
  ELSE
    -- Add
    INSERT INTO service_type(type_code, type_name, price_daily, price_daily_discounted, price_monthly, price_monthly_discounted, remarks, user_id, creation_date, last_modified_date) VALUES (pTypeCode, pTypeName, pPriceDaily, pPriceDailyDiscounted, pPriceMonthly, pPriceMonthlyDiscounted, pRemarks, pUserId, now(), now());
  END IF;

  COMMIT;
END
$$

--
-- Definition for procedure pRegisterMemberWorkout
--
DROP PROCEDURE IF EXISTS pRegisterMemberWorkout$$
CREATE PROCEDURE pRegisterMemberWorkout(IN pMemberId INT, IN pMemberType VARCHAR(25), IN pMonthlyActive VARCHAR(5), IN pServiceType VARCHAR(255), IN pAmount DECIMAL, IN pPaid VARCHAR(10), IN pOtherInfo TEXT, IN pMonthStart VARCHAR(25), IN pMonthEnd VARCHAR(25), IN pUserId INT(10))
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for Registering Member Workout'
BEGIN
  INSERT INTO workout_sales(member_id, workout_date, workout_hour, service_type, rendered_amount, paid, other_info, creation_date) VALUES(pMemberId, now(), hour(now()), pServiceType, pAmount, pPaid, pOtherInfo, now());

  IF pMemberType = 'Monthly' AND pMonthlyActive = 'No' AND !ISNULL(pMonthStart) AND !ISNULL(pMonthEnd) THEN
    UPDATE membership_type SET
      type = pMemberType,
      service_type = pServiceType,
      monthly_startdate = pMonthStart,
      monthly_enddate = pMonthEnd,
      last_modified_date = now(),
      user_id = pUserId
    WHERE member_id = pMemberId;
  ELSEIF pMemberType = 'Daily' AND pMonthlyActive = 'No' AND ISNULL(pMonthStart) AND ISNULL(pMonthEnd) THEN
    UPDATE membership_type SET
      type = pMemberType,
      last_modified_date = now(),
      user_id = pUserId
    WHERE member_id = pMemberId;
  END IF;

  COMMIT;
END
$$

--
-- Definition for procedure pRemoveItem
--
DROP PROCEDURE IF EXISTS pRemoveItem$$
CREATE PROCEDURE pRemoveItem(IN pItemId VARCHAR(255))
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for removing an item.'
BEGIN
  DECLARE nItemCount INT(10);

  DECLARE exit handler for sqlexception
    BEGIN
      -- ERROR
    ROLLBACK;
  END;
  
  DECLARE exit handler for sqlwarning
   BEGIN
      -- WARNING
   ROLLBACK;
  END;

  SELECT COUNT(is1.id) INTO nItemCount FROM item_sales is1 WHERE is1.item_id = pItemId;

  IF 0 = nItemCount THEN
    START TRANSACTION;
    DELETE FROM ITEM_SALES WHERE ITEM_ID = pItemId;
    DELETE FROM ITEM WHERE ID = pItemId;
    COMMIT;
  END IF;

END
$$

--
-- Definition for procedure pRemoveMember
--
DROP PROCEDURE IF EXISTS pRemoveMember$$
CREATE PROCEDURE pRemoveMember(IN pMemberId VARCHAR(255))
  SQL SECURITY INVOKER
BEGIN
  DECLARE nMemberCount INT(10);

  DECLARE exit handler for sqlexception
    BEGIN
      -- ERROR
    ROLLBACK;
  END;
  
  DECLARE exit handler for sqlwarning
   BEGIN
      -- WARNING
   ROLLBACK;
  END;

  SELECT COUNT(ws.id) INTO nMemberCount FROM workout_sales ws WHERE ws.member_id = pMemberId;

  IF 0 = nMemberCount THEN
    START TRANSACTION;
    DELETE FROM MEMBERSHIP_TYPE WHERE MEMBER_ID = pMemberId;
    DELETE FROM MEMBER WHERE ID = pMemberId;
    COMMIT;
  END IF;

END
$$

--
-- Definition for procedure pRemoveUser
--
DROP PROCEDURE IF EXISTS pRemoveUser$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pRemoveUser(IN pUserId INT)
BEGIN
  UPDATE USER SET is_active = 0 WHERE id = pUserId;
  COMMIT;
END
$$

--
-- Definition for procedure pUpdateMasterPassword
--
DROP PROCEDURE IF EXISTS pUpdateMasterPassword$$
CREATE PROCEDURE pUpdateMasterPassword(IN pMasterPassword VARCHAR(255), IN pNewPassword VARCHAR(255))
  SQL SECURITY INVOKER
BEGIN
  IF !ISNULL(pMasterPassword) AND !ISNULL(pNewPassword) THEN
    IF 0 < fnCheckMasterPassword(pMasterPassword) THEN
      UPDATE user
      SET password = md5(pNewPassword)
      WHERE username = 'administrator';
      COMMIT;
    END IF;
  END IF;
END
$$

--
-- Definition for procedure pUpdateSoldItemsGrandTotal
--
DROP PROCEDURE IF EXISTS pUpdateSoldItemsGrandTotal$$
CREATE PROCEDURE pUpdateSoldItemsGrandTotal(IN pItemSaleId INT, IN pItemAmount DECIMAL)
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for adding item price to grand total'
BEGIN
  declare grandTotal decimal;

  if !isnull(pItemSaleId) and !isnull(pItemAmount) then
    select grand_total into grandTotal  from vw_itemsales_grandtotal where id = pItemSaleId;

    update item_sales set 
      grand_total_amount= grandTotal + pItemAmount
    where id = pItemSaleId;

    commit;
  end if;

END
$$

--
-- Definition for procedure pUpdateUserPassword
--
DROP PROCEDURE IF EXISTS pUpdateUserPassword$$
CREATE PROCEDURE pUpdateUserPassword(IN pUsername VARCHAR(50), IN pUserPassword VARCHAR(100), IN pNewPassword VARCHAR(100))
  SQL SECURITY INVOKER
  COMMENT 'Stored Procedure for changing user password'
BEGIN
  IF !ISNULL(pUsername) AND !ISNULL(pUserPassword) AND !ISNULL(pNewPassword) THEN
    IF 0 < fnCheckUserLogin(pUsername, pUserPassword) THEN
      UPDATE user
      SET password = md5(pNewPassword)
      WHERE username = pUsername;
      COMMIT;
    END IF;
  END IF;
END
$$

--
-- Definition for function fnCheckMasterPassword
--
DROP FUNCTION IF EXISTS fnCheckMasterPassword$$
CREATE FUNCTION fnCheckMasterPassword(masterPassword varchar(255))
  RETURNS tinyint(4)
  SQL SECURITY INVOKER
BEGIN
  DECLARE sPassword varchar(100);

  SELECT
    u.password INTO sPassword
  FROM user u
  WHERE u.username = 'administrator'
  LIMIT 1;

  RETURN IF(sPassword = md5(masterPassword), 1, 0);
END
$$

--
-- Definition for function fnCheckUniqueUser
--
DROP FUNCTION IF EXISTS fnCheckUniqueUser$$
CREATE FUNCTION fnCheckUniqueUser(pFirstname VARCHAR(50), pLastname VARCHAR(50))
  RETURNS int(11)
  SQL SECURITY INVOKER
  COMMENT 'Function for checking for unique user first and last names.'
BEGIN
  DECLARE usersCount int(10);
  DECLARE nResult tinyint(1);

  SET nResult = 1;

  IF !ISNULL(pFirstname) AND !ISNULL(pLastname) THEN
    SELECT COUNT(u.id) INTO usersCount
    FROM user u
    WHERE
      lower(u.firstname) = lower(pFirstname) AND lower(u.lastname) = lower(pLastname)
      LIMIT 1;
    IF 0 < usersCount THEN
      SET nResult = 0;
    END IF;
  END IF;

RETURN nResult;
END
$$

--
-- Definition for function fnCheckUserLogin
--
DROP FUNCTION IF EXISTS fnCheckUserLogin$$
CREATE FUNCTION fnCheckUserLogin(pUsername varchar(100), pPassword varchar(100))
  RETURNS int(11)
  SQL SECURITY INVOKER
BEGIN
  DECLARE sPassword varchar(100);
  DECLARE nResult tinyint(1);

  SET nResult = 0;

  IF !ISNULL(pUsername) AND !ISNULL(pPassword) THEN
    SELECT
      u.password INTO sPassword
    FROM user u
    WHERE u.username = pUsername and is_active = 1
    LIMIT 1;
    SET nResult = IF(sPassword = md5(pPassword), 1, 0);
  END IF;

  RETURN nResult;
END
$$

DELIMITER ;

--
-- Definition for view vw_item_sales
--
DROP VIEW IF EXISTS vw_item_sales CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_item_sales
AS
	select `isl`.`id` AS `id`,`isd`.`item_sales_id` AS `item_sales_id`,`isd`.`item_id` AS `item_id`,`i`.`name` AS `item_name`,`isd`.`qty` AS `item_quantity`,`isd`.`unit_total` AS `unit_total`,`isd`.`remarks` AS `remarks`,`isl`.`sales_date` AS `sales_date`,date_format(`isl`.`sales_date`,'%Y') AS `year_group`,concat(date_format(`isl`.`sales_date`,'%M'),'-',date_format(`isl`.`sales_date`,'%Y')) AS `sales_group`,`isl`.`grand_total_amount` AS `grand_total_amount`,`isl`.`member_id` AS `member_id`,if(isnull(`isl`.`member_id`),'Anonymous',trim(concat(ifnull(`m`.`firstname`,''),' ',if((`m`.`middlename` is not null),concat(substr(`m`.`middlename`,1,1),'. '),''),ifnull(`m`.`lastname`,'')))) AS `customer_name`,`isl`.`user_id` AS `user_id` from (((`item_sales` `isl` left join `item_sales_details` `isd` on((`isd`.`item_sales_id` = `isl`.`id`))) left join `item` `i` on((`i`.`id` = `isd`.`item_id`))) left join `member` `m` on((`m`.`id` = `isl`.`member_id`)));

--
-- Definition for view vw_items
--
DROP VIEW IF EXISTS vw_items CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_items
AS
	select `i`.`id` AS `item_id`,`i`.`name` AS `item_name`,`i`.`price` AS `item_price`,`i`.`other_info` AS `item_infos`,`i`.`user_id` AS `user_id` from `item` `i`;

--
-- Definition for view vw_members
--
DROP VIEW IF EXISTS vw_members CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_members
AS
	select `m`.`id` AS `member_id`,`m`.`firstname` AS `firstname`,`m`.`lastname` AS `lastname`,`m`.`middlename` AS `middlename`,trim(concat(ifnull(`m`.`firstname`,''),' ',if((`m`.`middlename` is not null),concat(substr(`m`.`middlename`,1,1),'. '),''),ifnull(`m`.`lastname`,''))) AS `member_name`,`m`.`contactno` AS `contactno`,`m`.`address` AS `address`,`m`.`birthdate` AS `birthdate`,`m`.`gender` AS `gender`,`m`.`emergency_contact_person` AS `emergency_contact_person`,`m`.`emergency_contact_number` AS `emergency_contact_number`,`m`.`emergency_contact_relationship` AS `emergency_contact_relationship`,`st`.`type_code` AS `service_type_code`,`st`.`type_name` AS `service_type`,`st`.`price_daily` AS `price_daily`,`st`.`price_daily_discounted` AS `price_daily_discounted`,`st`.`price_monthly` AS `price_monthly`,`st`.`price_monthly_discounted` AS `price_monthly_discounted`,`mt`.`monthly_startdate` AS `monthly_startdate`,`mt`.`monthly_enddate` AS `monthly_enddate`,if((now() between `mt`.`monthly_startdate` and `mt`.`monthly_enddate`),'Monthly','Daily') AS `member_type`,if(`mt`.`discounted`,'Yes','No') AS `has_discount`,if((now() between `mt`.`monthly_startdate` and `mt`.`monthly_enddate`),if((now() between `mt`.`monthly_startdate` and `mt`.`monthly_enddate`),0,if((`mt`.`discounted` and (`st`.`price_monthly_discounted` is not null)),`st`.`price_monthly_discounted`,`st`.`price_monthly`)),if((`mt`.`discounted` and (`st`.`price_daily_discounted` is not null)),`st`.`price_daily_discounted`,`st`.`price_daily`)) AS `amount_due` from ((`member` `m` join `membership_type` `mt` on((`mt`.`member_id` = `m`.`id`))) left join `service_type` `st` on((`st`.`type_code` = `mt`.`service_type`))) where (`mt`.`member_id` <> 1) order by `mt`.`type`;

--
-- Definition for view vw_sold_items
--
DROP VIEW IF EXISTS vw_sold_items CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items
AS
	select `isd`.`item_id` AS `item_id`,`i`.`name` AS `item_name`,`isd`.`qty` AS `item_quantity`,`isd`.`unit_total` AS `unit_total`,cast(`isl`.`sales_date` as date) AS `sales_date`,date_format(`isl`.`sales_date`,'%Y') AS `year_group`,concat(date_format(`isl`.`sales_date`,'%M'),'-',date_format(`isl`.`sales_date`,'%Y')) AS `sales_group` from (((`item_sales` `isl` left join `item_sales_details` `isd` on((`isd`.`item_sales_id` = `isl`.`id`))) left join `item` `i` on((`i`.`id` = `isd`.`item_id`))) left join `member` `m` on((`m`.`id` = `isl`.`member_id`)));

--
-- Definition for view vw_users
--
DROP VIEW IF EXISTS vw_users CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_users
AS
	select `u`.`id` AS `user_id`,`u`.`firstname` AS `firstname`,`u`.`lastname` AS `lastname`,`u`.`middlename` AS `middlename`,trim(concat(ifnull(`u`.`firstname`,''),' ',if((`u`.`middlename` is not null),concat(substr(`u`.`middlename`,1,1),'. '),''),ifnull(`u`.`lastname`,''))) AS `user_name`,`u`.`contactno` AS `contactno`,`u`.`address` AS `address`,`u`.`birthdate` AS `birthdate`,`u`.`gender` AS `gender`,`u`.`username` AS `username`,`u`.`password` AS `password`,`u`.`role_type` AS `role_type`,`u`.`creation_date` AS `creation_date`,`u`.`last_modified_date` AS `last_modified_date` from `user` `u` where ((`u`.`id` > 1) and (`u`.`is_active` = 1));

--
-- Definition for view vw_workout_sales
--
DROP VIEW IF EXISTS vw_workout_sales CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_sales
AS
	select `ws`.`id` AS `id`,trim(concat(ifnull(`m`.`firstname`,''),' ',if((`m`.`middlename` is not null),concat(substr(`m`.`middlename`,1,1),'. '),''),ifnull(`m`.`lastname`,''))) AS `member_name`,`st`.`type_name` AS `service_type_name`,`mt`.`type` AS `membership_type`,if(`mt`.`discounted`,'Yes','No') AS `has_discount`,`ws`.`rendered_amount` AS `rendered_amount`,`ws`.`workout_date` AS `workout_date`,date_format(`ws`.`creation_date`,'%r') AS `workout_time`,date_format(`ws`.`creation_date`,'%Y') AS `year_group`,concat(date_format(`ws`.`creation_date`,'%M'),'-',date_format(`ws`.`creation_date`,'%Y')) AS `sales_group`,`ws`.`paid` AS `payment_status` from (((`workout_sales` `ws` join `service_type` `st` on((`st`.`type_code` = `ws`.`service_type`))) join `member` `m` on((`m`.`id` = `ws`.`member_id`))) join `membership_type` `mt` on((`ws`.`member_id` = `mt`.`member_id`))) order by `ws`.`creation_date`;

--
-- Definition for view vw_workout_sales_details
--
DROP VIEW IF EXISTS vw_workout_sales_details CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_sales_details
AS
	select `ws`.`id` AS `id`,`ws`.`workout_date` AS `workout_date`,`ws`.`member_id` AS `member_id`,`m`.`firstname` AS `firstname`,`m`.`lastname` AS `lastname`,`m`.`middlename` AS `middlename`,trim(concat(ifnull(`m`.`firstname`,''),' ',if((`m`.`middlename` is not null),concat(substr(`m`.`middlename`,1,1),'. '),''),ifnull(`m`.`lastname`,''))) AS `member_name`,`m`.`contactno` AS `contactno`,`m`.`address` AS `address`,`m`.`birthdate` AS `birthdate`,`m`.`gender` AS `gender`,`ws`.`service_type` AS `service_type_code`,`st`.`type_name` AS `service_type_name`,if((now() between `mt`.`monthly_startdate` and `mt`.`monthly_enddate`),'Monthly','Daily') AS `member_type`,if(`mt`.`discounted`,'Yes','No') AS `has_discount`,`mt`.`monthly_startdate` AS `monthly_startdate`,`mt`.`monthly_enddate` AS `monthly_enddate`,`ws`.`rendered_amount` AS `rendered_amount`,`ws`.`other_info` AS `other_info`,`ws`.`paid` AS `paid`,`ws`.`user_id` AS `user_id` from ((((`workout_sales` `ws` join `member` `m` on((`m`.`id` = `ws`.`member_id`))) join `membership_type` `mt` on((`mt`.`member_id` = `m`.`id`))) join `user` `u` on((`u`.`id` = `ws`.`user_id`))) join `service_type` `st` on((`st`.`type_code` = `ws`.`service_type`)));

--
-- Definition for view vw_itemsales_grandtotal
--
DROP VIEW IF EXISTS vw_itemsales_grandtotal CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_itemsales_grandtotal
AS
	select `vis`.`id` AS `id`,`vis`.`grand_total_amount` AS `grand_total` from `vw_item_sales` `vis` group by `vis`.`id`;

--
-- Definition for view vw_sold_items_daily
--
DROP VIEW IF EXISTS vw_sold_items_daily CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_daily
AS
	select `vw_sold_items`.`sales_date` AS `sales_date`,`vw_sold_items`.`item_id` AS `item_id`,`vw_sold_items`.`item_name` AS `item_name`,sum(`vw_sold_items`.`item_quantity`) AS `item_count`,sum(`vw_sold_items`.`unit_total`) AS `total` from `vw_sold_items` group by `vw_sold_items`.`sales_date`,`vw_sold_items`.`item_id`,`vw_sold_items`.`item_name`;

--
-- Definition for view vw_sold_items_monthly
--
DROP VIEW IF EXISTS vw_sold_items_monthly CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_monthly
AS
	select `vw_sold_items`.`sales_group` AS `sales_group`,`vw_sold_items`.`item_id` AS `item_id`,`vw_sold_items`.`item_name` AS `item_name`,sum(`vw_sold_items`.`item_quantity`) AS `item_count`,sum(`vw_sold_items`.`unit_total`) AS `total` from `vw_sold_items` group by `vw_sold_items`.`sales_group`,`vw_sold_items`.`item_id`,`vw_sold_items`.`item_name`;

--
-- Definition for view vw_sold_items_yearly
--
DROP VIEW IF EXISTS vw_sold_items_yearly CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_yearly
AS
	select `vw_sold_items`.`year_group` AS `year_group`,`vw_sold_items`.`item_id` AS `item_id`,`vw_sold_items`.`item_name` AS `item_name`,sum(`vw_sold_items`.`item_quantity`) AS `item_count`,sum(`vw_sold_items`.`unit_total`) AS `total` from `vw_sold_items` group by `vw_sold_items`.`year_group`,`vw_sold_items`.`item_id`,`vw_sold_items`.`item_name`;

--
-- Definition for view vw_workout_daily_sales
--
DROP VIEW IF EXISTS vw_workout_daily_sales CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_daily_sales
AS
	select `a`.`workout_date` AS `workout_date`,sum(`a`.`rendered_amount`) AS `daily_sales`,count(`a`.`id`) AS `transaction_count` from `vw_workout_sales` `a` where (`a`.`payment_status` = 'Paid') group by `a`.`workout_date`;

--
-- Definition for view vw_workout_monthly_sales
--
DROP VIEW IF EXISTS vw_workout_monthly_sales CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_monthly_sales
AS
	select `a`.`sales_group` AS `sales_group`,sum(`a`.`rendered_amount`) AS `monthly_sales`,count(`a`.`id`) AS `transaction_count` from `vw_workout_sales` `a` where (`a`.`payment_status` = 'Paid') group by `a`.`sales_group`;

--
-- Definition for view vw_workout_type_sales
--
DROP VIEW IF EXISTS vw_workout_type_sales CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_type_sales
AS
	select `vw_workout_sales`.`workout_date` AS `workout_date`,`vw_workout_sales`.`service_type_name` AS `service_type_name`,sum(`vw_workout_sales`.`rendered_amount`) AS `total` from `vw_workout_sales` group by `vw_workout_sales`.`workout_date`,`vw_workout_sales`.`service_type_name`;

--
-- Definition for view vw_item_daily_sales_total
--
DROP VIEW IF EXISTS vw_item_daily_sales_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_item_daily_sales_total
AS
	select `vw_sold_items_daily`.`sales_date` AS `sales_date`,sum(`vw_sold_items_daily`.`total`) AS `total_sales` from `vw_sold_items_daily` group by `vw_sold_items_daily`.`sales_date`;

--
-- Definition for view vw_sold_items_daily_total
--
DROP VIEW IF EXISTS vw_sold_items_daily_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_daily_total
AS
	select `vw_sold_items_daily`.`sales_date` AS `sales_date`,sum(`vw_sold_items_daily`.`total`) AS `total_sales` from `vw_sold_items_daily` group by `vw_sold_items_daily`.`sales_date`;

--
-- Definition for view vw_sold_items_monthly_total
--
DROP VIEW IF EXISTS vw_sold_items_monthly_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_monthly_total
AS
	select `vw_sold_items_monthly`.`sales_group` AS `sales_group`,sum(`vw_sold_items_monthly`.`total`) AS `total_sales` from `vw_sold_items_monthly` group by `vw_sold_items_monthly`.`sales_group`;

--
-- Definition for view vw_sold_items_yearly_total
--
DROP VIEW IF EXISTS vw_sold_items_yearly_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_sold_items_yearly_total
AS
	select `vw_sold_items_yearly`.`year_group` AS `year_group`,sum(`vw_sold_items_yearly`.`total`) AS `total_sales` from `vw_sold_items_yearly` group by `vw_sold_items_yearly`.`year_group`;

--
-- Definition for view vw_workout_sales_total
--
DROP VIEW IF EXISTS vw_workout_sales_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_workout_sales_total
AS
	select `vw_workout_type_sales`.`workout_date` AS `workout_date`,sum(`vw_workout_type_sales`.`total`) AS `total_sales` from `vw_workout_type_sales` group by `vw_workout_type_sales`.`workout_date`;

--
-- Definition for view vw_dailysales_total
--
DROP VIEW IF EXISTS vw_dailysales_total CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW vw_dailysales_total
AS
	select `vw_workout_sales_total`.`workout_date` AS `transaction_date`,'Workouts' AS `transaction_type`,`vw_workout_sales_total`.`total_sales` AS `total_sales` from `vw_workout_sales_total` union select `vw_sold_items_daily_total`.`sales_date` AS `transaction_date`,'Products' AS `transaction_type`,`vw_sold_items_daily_total`.`total_sales` AS `total_sales` from `vw_sold_items_daily_total`;


-- 
-- Dumping data for table service_type
--
INSERT INTO service_type VALUES
('boxing', 'Fitness Boxing', 60.00, 50.00, 600.00, 500.00, 'Fitness Boxing', 1, '2015-09-10 09:37:03', '2015-09-10 09:37:07'),
('weights', 'Weights', 45.00, 40.00, 450.00, 400.00, 'Weights', 1, '2015-09-10 09:38:39', '2015-09-10 09:38:41');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'administrator', 'bfa1644c97b4269d2327653c70dff4d5', 'GrmSys', 'Administrator', 'Admin', NULL, NULL, NULL, 'M', 1, 'administrator', '2015-08-21 23:49:07', '2015-08-21 23:49:09');



INSERT INTO member(id, firstname, lastname, emergency_contact_person, emergency_contact_number, emergency_contact_relationship, creation_date, last_modified_date, user_id)
  VALUES (1, 'Member', 'Anonymous', 'n/a', 'n/a', 'n/a', NOW(), NOW(), 1);

INSERT INTO membership_type(member_id, creation_date, user_id) VALUES(1, NOW(), 1);
  COMMIT;